#!/bin/sh

clear

# For each instance of "Machine" change for the name of your current machine.
# Change the path for your log file to what you want to use.
# This log file will become large. It is suggested to be kept on a network location.

logfile=/var/log/Machine-Update.log
dt=$(date '+%d/%m/%Y %H:%M:%S')

echo -e "\n\n$dt $USER Machine Update" >> $logfile
echo ""
echo "Updating Machine, Please wait."
echo ""

apt-get update -y | tee -a $logfile
apt-get upgrade -y | tee -a $logfile
apt-get dist-upgrade -y | tee -a $logfile
apt-get autoremove -y | tee -a $logfile
apt-get autoclean -y | tee -a $logfile
