#!/bin/sh

clear

logfile=/var/log/Machine-Update.log
dt=$(date '+%d/%m/%Y %H:%M:%S')

echo -e "\n\n$dt $USER Machine Update" >> $logfile
echo ""
echo "Updating Machine, Please wait."
echo ""

apt-get update -y | tee -a $logfile
apt-get upgrade -y | tee -a $logfile
apt-get dist-upgrade -y | tee -a $logfile
apt-get autoremove -y | tee -a $logfile
apt-get autoclean -y | tee -a $logfile
